;; -*- mode: eask; lexical-binding: t -*-

(package "google-translate-cli"
         "1.0.0"
         "A command-line interface for Google Translate")

(website-url "https://github.com/emacs-eine/google-translate-cli")
(keywords "convenience")

(package-file "google-translate-cli.el")
(files "bin")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "google-translate")
(depends-on "commander")
(depends-on "msgu")
